import { Place } from '@/types/place';

export const MOCK_PLACES: Place[] = [
  // ===== Bangkok =====
  {
    id: 'bkk-1',
    name: 'Gaggan Anand',
    category: 'Fine Dining',
    price_range: '$$$',
    rating: 4.9,
    personal_notes:
      'ประสบการณ์ที่ไม่เหมือนใคร อาหาร Progressive Indian รสชาติล้ำมาก เมนูมีแต่ Emoji ไม่มีชื่อ ต้องลอง!',
    lat: 13.7482,
    lng: 100.5386,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=13.7482,100.5386',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'bkk-2',
    name: 'Or Tor Kor Market',
    category: 'Street Food',
    price_range: '$',
    rating: 4.6,
    personal_notes:
      'ตลาดสดชั้นดีของกรุงเทพ ผักผลไม้สดมาก ของกินเยอะมาก มีทั้งส้มตำ ข้าวมันไก่ ผัดไทย ราคาย่อมเยา',
    lat: 13.7997,
    lng: 100.5501,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=13.7997,100.5501',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'bkk-3',
    name: 'Cé La Vi Bangkok',
    category: 'Bar & Cafe',
    price_range: '$$$',
    rating: 4.4,
    personal_notes:
      'Rooftop bar ชั้น 39 ของ Sathorn Square วิวสวยมาก เหมาะกับนั่ง Chill ยามเย็น Cocktail เด็ด',
    lat: 13.7231,
    lng: 100.5306,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=13.7231,100.5306',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-01-17T10:00:00Z',
  },
  {
    id: 'bkk-4',
    name: 'Seafood Market & Restaurant',
    category: 'Sea Food',
    price_range: '$$',
    rating: 4.3,
    personal_notes:
      'ร้านอาหารทะเลขนาดใหญ่ เลือกวัตถุดิบสดเองได้เลย ปลาหมึก กุ้ง ปูสด บรรยากาศดี เหมาะกับปาร์ตี้ครอบครัว',
    lat: 13.7225,
    lng: 100.5200,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=13.7225,100.5200',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-01-18T10:00:00Z',
  },
  {
    id: 'bkk-5',
    name: 'Platinum Buffet Bangkok',
    category: 'Buffet',
    price_range: '$$',
    rating: 4.2,
    personal_notes:
      'บุฟเฟ่ต์อาหารญี่ปุ่น+นานาชาติ คุ้มค่ามาก มีซูชิ ซาชิมิ ปิ้งย่าง เปิดบ่ายถึงดึก เหมาะไปกับเพื่อน',
    lat: 13.7460,
    lng: 100.5340,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=13.7460,100.5340',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-01-19T10:00:00Z',
  },

  // ===== Tokyo =====
  {
    id: 'tky-1',
    name: 'Sukiyabashi Jiro Honten',
    category: 'Fine Dining',
    price_range: '$$$',
    rating: 5.0,
    personal_notes:
      'ร้านซูชิระดับตำนาน มิชลิน 3 ดาว เจ้าของคือคุณจิโร่ โอโนะ อายุ 90 กว่าปีแต่ยังทำเองอยู่ จองล่วงหน้าหลายเดือน',
    lat: 35.6720,
    lng: 139.7634,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=35.6720,139.7634',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'tky-2',
    name: 'Tsukiji Outer Market',
    category: 'Street Food',
    price_range: '$',
    rating: 4.7,
    personal_notes:
      'ตลาดปลาที่มีชื่อเสียงโด่งดัง แม้ตลาดในจะย้ายไปแล้ว แต่ Outer Market ยังสดใหม่ อาหารทะเลสดมาก ทามาโก้ยากิอร่อยมาก',
    lat: 35.6654,
    lng: 139.7707,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=35.6654,139.7707',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-02-02T10:00:00Z',
  },
  {
    id: 'tky-3',
    name: 'Gonpachi Nishi-Azabu',
    category: 'Bar & Cafe',
    price_range: '$$',
    rating: 4.4,
    personal_notes:
      'บรรยากาศเหมือนในหนัง Kill Bill จริงๆ อาหารญี่ปุ่นดั้งเดิม บรรยากาศ Samurai ไฟไม้ไผ่สลัวๆ เท่มาก',
    lat: 35.6605,
    lng: 139.7275,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=35.6605,139.7275',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-02-03T10:00:00Z',
  },
  {
    id: 'tky-4',
    name: 'Zauo Fishing Restaurant',
    category: 'Sea Food',
    price_range: '$$',
    rating: 4.5,
    personal_notes:
      'ร้านอาหารทะเลแนวใหม่ นั่งบนเรือแล้วตกปลาเองในร้าน! ปลาที่ตกได้จะถูกนำไปปรุงเลย สุดแปลกและสนุกมาก',
    lat: 35.7022,
    lng: 139.7002,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=35.7022,139.7002',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-02-04T10:00:00Z',
  },
  {
    id: 'tky-5',
    name: 'Kura Sushi — Conveyor Belt',
    category: 'Restaurant',
    price_range: '$',
    rating: 4.3,
    personal_notes:
      'Conveyor Belt Sushi สไตล์ญี่ปุ่นแท้ๆ จานละ 100 เยน มีระบบ Capsule Toy เมื่อส่งจาน 5 ใบ สนุกมาก เหมาะกับเด็ก',
    lat: 35.6942,
    lng: 139.7032,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=35.6942,139.7032',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    created_at: '2024-02-05T10:00:00Z',
  },
];
